defaults:
    addr: localhost:8000
    postgres_host: "localhost"
    postgres_port: 5432
    postgres_user: ""
    postgres_pass: ""
    postgres_db: "service_data"
    postgres_max_idle_conns: 0
    postgres_max_open_conns: 5
    allowed_origins: "*"
